### ISSUE TITLE
rename to "colourpiler" vs "colorpiler"? (World vs American)

### ISSUE THREAD

**Issue by daattali** [ropenscilabs/colorpiler#1]
Just a suggestion. Most packages seem to prefer the international spelling rather than the American one

**Comment by richfitz** [comment]
I obviously endorse this but Vince and Mika _are_ Americans and we were in SF so it seemed OK :stuck_out_tongue_winking_eye:

RColorBrewer is u-less so there's precedent.  I think that harmonising the names of the functions so both work is probably a reasonable compromise though.

**Comment by maelle** [comment]
This repo has been archived, cf [our package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages).
