### ISSUE TITLE
Add unique id to each palette

### ISSUE THREAD

**Issue by daattali** [ropenscilabs/colorpiler#2]
It'd be useful to have an ID for each palette.  Unless you want the name to be the uniquely identifying field, and want to restrict it to not having spaces

**Comment by richfitz** [comment]
The name is the unique ID because it is the filename in colorpile.  It is enforced by the schema not to have spaces (or "/" characters) though we don't at this point check that the declared name and the filename are the same (but that is in a TODO somewhere)

**Comment by daattali** [comment]
Ah, ok, so there IS a "unique" ID already. Cool :+1:
