### ISSUE TITLE
Suggestion: use shinyjs::colourPicker() to CREATE a colour palette

### ISSUE THREAD

**Issue by daattali** [ropenscilabs/colorpiler#4]
This package is awesome for sharing and retrieving colour palettes.

But just last week I created a gadget that lets you _create_ colour palettes easily, by visually selecting colours.  It fits so perfectly with this package as the first step before you share a palette since selecting the HEX colours was not an easy task using R before.

Take a look at `shinyjs::colourPicker()` and add it to the README if you agree  (I know it sounds like self advertising, but I really do think it fits perfectly here)

**Comment by richfitz** [comment]
We actually talked about this on Friday afternoon :smile_cat:

**Comment by maelle** [comment]
This repo has been archived, cf [our package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages).
