### ISSUE TITLE
demo_colorpile() is insufficient to glimpse a color scale

### ISSUE THREAD

**Issue by adrfantini** [ropenscilabs/colorpiler#5]
As it is, `demo_colorpile()` only lets you see three distinct colours in a palette, which is not enough to see how a palette is like. Brewer supports at least 9 colours in all palettes so `demo_colorpile()` should provide example plot(s) with at least that many colours.

**Comment by maelle** [comment]
This repo has been archived, cf [our package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages).
